apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "ai-service"
        vault.hashicorp.com/agent-inject-secret-config: "kv/data/ai-service"
        vault.hashicorp.com/agent-inject-template-config: |
          #!/bin/sh
          {{- with secret "kv/data/ai-service" -}}
          export OPENAI_API_KEY="{{ .Data.data.openai_api_key }}"
          export OPENAI_ORG_ID="{{ .Data.data.openai_org_id }}"
          export AZURE_OPENAI_API_KEY="{{ .Data.data.azure_openai_api_key }}"
          {{- end }}
        vault.hashicorp.com/log-level: "debug"
        vault.hashicorp.com/agent-inject-status: "update"  
    spec:
      serviceAccountName: ai-service
      containers:
      - name: ai-service
        image: prasad890/store-ai-service:latest
        # Use the container's original command from Dockerfile with prefix
        command: 
        - /bin/sh
        - -c
        args:
        - |
          if [ -f /vault/secrets/config ]; then
            echo "Sourcing Vault secrets..."
            source /vault/secrets/config
            env | grep -E 'OPENAI|AZURE'
          else
           echo "Error: Vault secrets file not found at /vault/secrets/config"
           ls -la /vault/secrets/
          fi
          exec uvicorn main:app --host 0.0.0.0 --port 5001
        ports:
        - containerPort: 5001
        env:
        - name: USE_AZURE_OPENAI
          value: "False"
        - name: AZURE_OPENAI_DALLE_DEPLOYMENT_NAME 
          value: "dall-e-3"
        - name: AZURE_OPENAI_DALLE_ENDPOINT
          value: "https://petclinic.openai.azure.com"
        - name: AZURE_OPENAI_API_VERSION
          value: "2024-02-15-preview"
        - name: USE_AZURE_AD
          value: "False"
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 128Mi
#        startupProbe:
#          httpGet:
#            path: /health
#            port: 5001
#          initialDelaySeconds: 60
#          failureThreshold: 3
#          periodSeconds: 5
#        readinessProbe:
#          httpGet:
#            path: /health
#            port: 5001
#          initialDelaySeconds: 3
#          failureThreshold: 10
#          periodSeconds: 10
#        livenessProbe:
#          httpGet:
#            path: /health
#            port: 5001
#          initialDelaySeconds: 3
#          failureThreshold: 10
#          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5001
    targetPort: 5001
  selector:
    app: ai-service