apiVersion: v1
kind: Pod
metadata:
  name: vault-test
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "ai-service"
    vault.hashicorp.com/agent-inject-secret-config: "kv/data/ai-service"
    vault.hashicorp.com/agent-inject-template-config: |
      {{- with secret "kv/data/ai-service" -}}
      export OPENAI_API_KEY="{{ .Data.data.openai_api_key }}"
      export OPENAI_ORG_ID="{{ .Data.data.openai_org_id }}"
      export AZURE_OPENAI_API_KEY="{{ .Data.data.azure_openai_api_key }}"
      {{- end }}
spec:
  serviceAccountName: ai-service
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/sh", "-c", "ls -la /vault/secrets && cat /vault/secrets/config && sleep 3600 || echo 'Config not found' && sleep 3600"]