apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: istio-system
data:
  config.yaml: |
    auth:
      strategy: anonymous
    deployment:
      accessible_namespaces:
      - "**"
    external_services:
      prometheus:
        url: "http://prometheus.default:9090"
      grafana:
        enabled: true
        in_cluster_url: "http://grafana.istio-system:3000"
      tracing:
        enabled: true
        in_cluster_url: "http://tracing.istio-system:80/jaeger"
    server:
      port: 20001
      web_root: /kiali