apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8090"
spec:
  selector:
    name: cadvisor
  ports:
  - name: http
    port: 8090
    targetPort: 8090
    protocol: TCP