apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-exporter
  template:
    metadata:
      labels:
        app: mongodb-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9216"
    spec:
      containers:
      - name: mongodb-exporter
        image: percona/mongodb_exporter:0.36
        ports:
        - containerPort: 9216
          name: metrics
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017"
        resources:
          requests:
            cpu: 10m
            memory: 30Mi
          limits:
            cpu: 50m
            memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9216"
spec:
  selector:
    app: mongodb-exporter
  ports:
  - port: 9216
    targetPort: 9216
  type: ClusterIP