apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cadvisor
  namespace: default
spec:
  selector:
    matchLabels:
      name: cadvisor
  template:
    metadata:
      labels:
        name: cadvisor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: cadvisor
        image: gcr.io/cadvisor/cadvisor:v0.47.0
        args:
        - --port=8080
        - --housekeeping_interval=10s
        - --max_housekeeping_interval=15s
        - --event_storage_event_limit=default=0
        - --event_storage_age_limit=default=0
        - --disable_metrics=percpu,sched,tcp,udp,disk,diskIO,process,hugetlb,referenced_memory,cpu_topology,resctrl
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        securityContext:
          privileged: true
          runAsUser: 0
          runAsGroup: 0
        resources:
          requests:
            memory: 100Mi
            cpu: 50m
          limits:
            memory: 400Mi
            cpu: 300m
        volumeMounts:
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
        - name: var-run
          mountPath: /var/run
          readOnly: true
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: docker
          mountPath: /var/lib/docker
          readOnly: true
        - name: dev
          mountPath: /dev
          readOnly: true
      volumes:
      - name: rootfs
        hostPath:
          path: /
      - name: var-run
        hostPath:
          path: /var/run
      - name: sys
        hostPath:
          path: /sys
      - name: docker
        hostPath:
          path: /var/lib/docker
      - name: dev
        hostPath:
          path: /dev
      hostNetwork: true
      hostPID: true
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  selector:
    name: cadvisor
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP